var BaseSkill = 
{
	TapHurtUpRate : {
		Desc : "这位英雄的攻击力提升%d%",
		Type : SkillType.TapHurtUpRate,
	},
	TapCritRate : {
		Desc : "这位英雄的攻击力提升%d%",
		Type : SkillType.TapCritRate,
	},
	TapCritHurtRate : {
		Desc : "这位英雄的攻击力提升%d%",
		Type : SkillType.TapCritHurtRate,
	},
	DPSHurtUpRate : {
		Desc : "这位英雄的攻击力提升%d%",
		Type : SkillType.DPSHurtUpRate,
	},
	DPSHeroHurtUpRate : {
		Desc : "这位英雄的攻击力提升%d%",
		Type : SkillType.DPSHeroHurtUpRate,
	},
	AllAttackUpRate : {
		Desc : "这位英雄的攻击力提升%d%",
		Type : SkillType.AllAttackUpRate,
	},
	DPSToTapHurtRate : {
		Desc : "这位英雄的攻击力提升%d%",
		Type : SkillType.DPSToTapHurtRate,
	},
	DropGlodUpRate : {
		Desc : "这位英雄的攻击力提升%d%",
		Type : SkillType.DropGlodUpRate,
	},
	DropBoxGlodUpRate : {
		Desc : "这位英雄的攻击力提升%d%",
		Type : SkillType.DropBoxGlodUpRate,
	},
	BossHurtUpRate : {
		Desc : "这位英雄的攻击力提升%d%",
		Type : SkillType.BossHurtUpRate,
	},
	AppearBoxUpRate : {
		Desc : "这位英雄的攻击力提升%d%",
		Type : SkillType.AppearBoxUpRate,
	},
	BossBloodCutRate : {
		Desc : "这位英雄的攻击力提升%d%",
		Type : SkillType.BossBloodCutRate,
	},
	DropAll10TimeGlodUpRate : {
		Desc : "这位英雄的攻击力提升%d%",
		Type : SkillType.DropAll10TimeGlodUpRate,
	},
	DropBossGlodUpRate : {
		Desc : "这位英雄的攻击力提升%d%",
		Type : SkillType.DropBossGlodUpRate,
	},
	BossMakeHeroDiesCutRate : {
		Desc : "这位英雄的攻击力提升%d%",
		Type : SkillType.BossMakeHeroDiesCutRate,
	},
	HeroLevelGlodCutRate : {
		Desc : "这位英雄的攻击力提升%d%",
		Type : SkillType.HeroLevelGlodCutRate,
	},
	BossTimeUpRate : {
		Desc : "这位英雄的攻击力提升%d%",
		Type : SkillType.BossTimeUpRate,
	},
	RebirthRelicCountUpRate : {
		Desc : "这位英雄的攻击力提升%d%",
		Type : SkillType.RebirthRelicCountUpRate,
	},
	HeroRebirthTimeCutRate : {
		Desc : "这位英雄的攻击力提升%d%",
		Type : SkillType.HeroRebirthTimeCutRate,
	},
	MonsterCountCutReat : {
		Desc : "这位英雄的攻击力提升%d%",
		Type : SkillType.MonsterCountCutReat,
	},
	MainSkill1LastTimeUpRate : {
		Desc : "这位英雄的攻击力提升%d%",
		Type : SkillType.MainSkill1LastTimeUpRate,
	},
	MainSkill1CoolDownCutRate : {
		Desc : "这位英雄的攻击力提升%d%",
		Type : SkillType.MainSkill1CoolDownCutRate,
	},
	MainSkill2LastTimeUpRate : {
		Desc : "这位英雄的攻击力提升%d%",
		Type : SkillType.MainSkill1LastTimeUpRate,
	},
	MainSkill2CoolDownCutRate : {
		Desc : "这位英雄的攻击力提升%d%",
		Type : SkillType.MainSkill1CoolDownCutRate,
	},
	MainSkill3LastTimeUpRate : {
		Desc : "这位英雄的攻击力提升%d%",
		Type : SkillType.MainSkill1LastTimeUpRate,
	},
	MainSkill3CoolDownCutRate : {
		Desc : "这位英雄的攻击力提升%d%",
		Type : SkillType.MainSkill1CoolDownCutRate,
	},
	MainSkill1LastTimeUpRate : {
		Desc : "这位英雄的攻击力提升%d%",
		Type : SkillType.MainSkill1LastTimeUpRate,
	},
	MainSkill4CoolDownCutRate : {
		Desc : "这位英雄的攻击力提升%d%",
		Type : SkillType.MainSkill1CoolDownCutRate,
	},
	MainSkill5LastTimeUpRate : {
		Desc : "这位英雄的攻击力提升%d%",
		Type : SkillType.MainSkill1LastTimeUpRate,
	},
	MainSkill5CoolDownCutRate : {
		Desc : "这位英雄的攻击力提升%d%",
		Type : SkillType.MainSkill1CoolDownCutRate,
	},
	MainSkill6LastTimeUpRate : {
		Desc : "这位英雄的攻击力提升%d%",
		Type : SkillType.MainSkill1LastTimeUpRate,
	},
	MainSkill6CoolDownCutRate : {
		Desc : "这位英雄的攻击力提升%d%",
		Type : SkillType.MainSkill1CoolDownCutRate,
	},
	Reincarnation : {
		Desc : "使用蜕变重新开始游戏，即可获得能用来换取神器的圣物。",
		Type : SkillType.Reincarnation,
	}
};

var Artifact = 
[
	{
		Name : "奥金利斧",
		Desc : "增加致死打击的伤害",
		Icon : res.icon_shenqi_1,
		BaseData : BaseSkill.TapHurtUpRate,
		MaxLevel : [0,5,10,15,20,30],
		Rate : 0.4,
	},
	{
		Name : "地狱火石",
		Desc : "缩减地狱火冷却",
		Icon : res.icon_shenqi_1,
		BaseData : BaseSkill.TapHurtUpRate,
		MaxLevel : [0,5,10,15,20,30],
		Rate : 0.4,
	},
	{
		Name : "上古骨弓",
		Desc : "增加快速射击时间",
		Icon : res.icon_shenqi_1,
		BaseData : BaseSkill.TapHurtUpRate,
		MaxLevel : [0,5,10,15,20,30],
		Rate : 0.4,
	},
	{
		Name : "守护者之杖",
		Desc : "DPS伤害额外提升百分比增加",
		Icon : res.icon_shenqi_1,
		BaseData : BaseSkill.TapHurtUpRate,
		MaxLevel : [0,5,10,15,20,30],
		Rate : 0.4,
	},
	{
		Name : "影之哀伤",
		Desc : "暴击几率百分比增加",
		Icon : res.icon_shenqi_1,
		BaseData : BaseSkill.TapHurtUpRate,
		MaxLevel : [0,5,10,15,20,30],
		Rate : 0.4,
	},
	{
		Name : "炎魔之锤",
		Desc : "暴击伤害百分比增加",
		Icon : res.icon_shenqi_1,
		BaseData : BaseSkill.TapHurtUpRate,
		MaxLevel : [0,5,10,15,20,30],
		Rate : 0.4,
	},
	{
		Name : "群星之怒",
		Desc : "点击攻击力提升百分比增加",
		Icon : res.icon_shenqi_1,
		BaseData : BaseSkill.TapHurtUpRate,
		MaxLevel : [0,5,10,15,20,30],
		Rate : 0.4,
	},
	{
		Name : "龙父之牙",
		Desc : "关卡小怪数量减少百分比",
		Icon : res.icon_shenqi_1,
		BaseData : BaseSkill.TapHurtUpRate,
		MaxLevel : [0,5,10,15,20,30],
		Rate : 0.4,
	},
	{
		Name : "埃辛诺斯战刃",
		Desc : "Boss血量减少",
		Icon : res.icon_shenqi_1,
		BaseData : BaseSkill.TapHurtUpRate,
		MaxLevel : [0,5,10,15,20,30],
		Rate : 0.4,
	},
	{
		Name : "巨龙之怒",
		Desc : "掉落黄金提升百分比增加",
		Icon : res.icon_shenqi_1,
		BaseData : BaseSkill.TapHurtUpRate,
		MaxLevel : [0,5,10,15,20,30],
		Rate : 0.4,
	},
	{
		Name : "瓦兰奈尔",
		Desc : "英雄升级消耗降低百分比",
		Icon : res.icon_shenqi_1,
		BaseData : BaseSkill.TapHurtUpRate,
		MaxLevel : [0,5,10,15,20,30],
		Rate : 0.4,
	},
	{
		Name : "雷霆逐风者",
		Desc : "Boss挑战时间增加百分比",
		Icon : res.icon_shenqi_1,
		BaseData : BaseSkill.TapHurtUpRate,
		MaxLevel : [0,5,10,15,20,30],
		Rate : 0.4,
	},
	{
		Name : "白虎之怒",
		Desc : "增加百分比电击伤害",
		Icon : res.icon_shenqi_1,
		BaseData : BaseSkill.TapHurtUpRate,
		MaxLevel : [0,5,10,15,20,30],
		Rate : 0.4,
	}
	
]
//技能信息
var SkillData = 
{
	Skill_1_1 : {
		Name : "火球术",
		Icon : res.icon_skill_1,
		BaseData : BaseSkill.TapHurtUpRate,
		Rate : 0.4,
	},
	Skill_1_2 : {
		Name : "技能名称",
		Icon : res.icon_skill_2,
		BaseData : BaseSkill.TapHurtUpRate,
		Rate : 0.4,
	},
	Skill_1_3 : {
		Name : "技能名称",
		Icon : res.icon_skill_3,
		BaseData : BaseSkill.TapHurtUpRate,
		Rate : 0.4,
	},
	Skill_1_4 : {
		Name : "技能名称",
		Icon : res.icon_skill_4,
		BaseData : BaseSkill.TapHurtUpRate,
		Rate : 0.4,
	},
	Skill_1_5 : {
		Name : "技能名称",
		Icon : res.icon_skill_5,
		BaseData : BaseSkill.TapHurtUpRate,
		Rate : 0.4,
	},
	Skill_1_6 : {
		Name : "技能名称",
		Icon : res.icon_skill_6,
		BaseData : BaseSkill.TapHurtUpRate,
		Rate : 0.4,
	},
	User : {
		Name : "无",
		Icon : res.icon_skill_1,
		BaseData : BaseSkill.TapHurtUpRate,
		Rate : 0.4,
	},
	User_1_1 : {
		Name : "致死打击",
		Icon : res.icon_skill_1,
		BaseData : BaseSkill.TapHurtUpRate,
		Rate : 0.4,
		ReleaseCD : 1,
		RecoveryCD : 10,
	},
	User_1_2 : {
		Name : "瞄准射击",
		Icon : res.icon_skill_1,
		BaseData : BaseSkill.TapHurtUpRate,
		Rate : 0.4,
		ReleaseCD : 1,
		RecoveryCD : 10,
	},
	User_1_3 : {
		Name : "炎爆术",
		Icon : res.icon_skill_1,
		BaseData : BaseSkill.TapHurtUpRate,
		Rate : 0.4,
		ReleaseCD : 1,
		RecoveryCD : 10,
	},
	User_2 : {
		Name : "影分身术",
		Icon : res.icon_skill_2,
		BaseData : BaseSkill.TapHurtUpRate,
		Rate : 0.4,
		ReleaseCD : 5,
		RecoveryCD : 60,
	},
	User_3 : {
		Name : "重击出击",
		Icon : res.icon_skill_3,
		BaseData : BaseSkill.TapHurtUpRate,
		Rate : 0.4,
		ReleaseCD : 10,
		RecoveryCD : 120,
	},
	User_4 : {
		Name : "嚎壕",
		Icon : res.icon_skill_4,
		BaseData : BaseSkill.TapHurtUpRate,
		Rate : 0.4,
		ReleaseCD : 10,
		RecoveryCD : 120,
	},
	User_5 : {
		Name : "狂战士愤怒",
		Icon : res.icon_skill_5,
		BaseData : BaseSkill.TapHurtUpRate,
		Rate : 0.4,
		ReleaseCD : 10,
		RecoveryCD : 120,
	},
	User_6 : {
		Name : "米达斯之手",
		Icon : res.icon_skill_6,
		BaseData : BaseSkill.TapHurtUpRate,
		Rate : 0.4,
		ReleaseCD : 10,
		RecoveryCD : 120,
	},
	User_7 : {
		Name : "蜕变",
		Icon : res.icon_skill_2,
		BaseData : BaseSkill.Reincarnation,
		Rate : 0.4,
		ReleaseCD : 0,
		RecoveryCD : 0,
	},
};


var PlayerJob =
{
	JobSoldier : {
		Index : 1,
		Desc : "战士是以近身格斗为主的职业：断筋技能可以使敌人致残而减慢速度(近战技能，减速50%）。而战斗怒吼可以提高队友们的战斗能力（100码范围内的所有小队和团队成员的攻击强度提高",
		AtkArmatureRes : res.effect_soldier_001,
		AtkArmatureName : "Effect_atk_warrior",
		AtkArmatureList : ["W1", "W2", "W3", "W4"],
		Skill : [SkillData.User,SkillData.User_1_1,SkillData.User_2,SkillData.User_3,SkillData.User_4,SkillData.User_5,SkillData.User_6,SkillData.User_7],
	},
	JobMaster : {
		Index : 2,
		Desc : "法师是著名网游《魔兽世界》中的职业之一，多个不同游戏版本在玩家中享有暴雪“亲儿子”之称。其定义为纯伤害输出型，法师们会用神秘的咒语摧毁他们的敌人，可操作性极强。",
		AtkArmatureRes : res.effect_master_001,
		AtkArmatureName : "Effect_atk_magister",
		AtkArmatureList : ["M1", "M2", "M3", "M4", "M5"],
		Skill : [SkillData.User,SkillData.User_1_3,SkillData.User_2,SkillData.User_3,SkillData.User_4,SkillData.User_5,SkillData.User_6,SkillData.User_7],
	},
	JobHunter : {
		Index : 3,
		Desc : "猎人是著名网游《魔兽世界》中的职业之一，其定义为伤害输出型。猎人在远距离与敌人作战，当他们使用弓箭或枪攻击敌人时，还会指挥宠物进行作战。前期版本一直有蓝条存在，从大灾变版（85级）开始变更为集中值。",
		AtkArmatureRes : res.effect_hunter_001,
		AtkArmatureName : "Effect_atk_hunter",
		AtkArmatureList : ["H1"],
		Skill : [SkillData.User,SkillData.User_1_2,SkillData.User_2,SkillData.User_3,SkillData.User_4,SkillData.User_5,SkillData.User_6,SkillData.User_7],
	}
};

var PlayerData = 
{
	Desc : "我是主角，我做主!",
	Icon : res.icon_hero_1,
	AtkBase : [0,0,2,0],
	MoneyBase : [0,0,2,0],
	SkillUnlock : [0, 10,50,100,200,400,600,600],
	Job : [ null ,PlayerJob.JobSoldier, PlayerJob.JobMaster, PlayerJob.JobHunter],
};

//英雄名字
var HeroData = 
[
	{

	},
	{
		Name : "维兰提斯",
		Desc : "你想玩火？但是火焰听我指挥",
		Icon : res.icon_hero_1,
		AtkBase : [0,0,0,1],
		MoneyBase : [0,2,1],
		SkillUnlock : [100,200,300,400,800,1000,1200],
		Skill : [SkillData.Skill_1_1,SkillData.Skill_1_2,SkillData.Skill_1_3,SkillData.Skill_1_4,SkillData.Skill_1_5,SkillData.Skill_1_6,SkillData.Skill_1_6],
	},
	{
		Name : "齐多里乌斯",
		Desc : "我不喜欢杀人，因为皮甲上的血太难洗了",
		Icon : res.icon_hero_1,
		AtkBase : [0,0,4,0],
		MoneyBase : [0,4,3],
		SkillUnlock : [100,200,300,400,800,1000,1200],
		Skill : [SkillData.Skill_1_1,SkillData.Skill_1_2,SkillData.Skill_1_3,SkillData.Skill_1_4,SkillData.Skill_1_5,SkillData.Skill_1_6,SkillData.Skill_1_6],
	},
	{
		Name : "桃丽丝",
		Desc : "我没说你可以躲开这次攻击，我是说，有我在你根本不需要躲",
		Icon : res.icon_hero_1,
		AtkBase : [0,0,6,0],
		MoneyBase : [0,6,5],
		SkillUnlock : [100,200,300,400,800,1000,1200],
		Skill : [SkillData.Skill_1_1,SkillData.Skill_1_2,SkillData.Skill_1_3,SkillData.Skill_1_4,SkillData.Skill_1_5,SkillData.Skill_1_6,SkillData.Skill_1_6],
	},
	{
		Name : "蕾米莉亚",
		Desc : "如果你只能选择一个技能，使用致死打击",
		Icon : res.icon_hero_1,
		AtkBase : [0,0,8,0],
		MoneyBase : [0,8,7],
		SkillUnlock : [100,200,300,400,800,1000,1200],
		Skill : [SkillData.Skill_1_1,SkillData.Skill_1_2,SkillData.Skill_1_3,SkillData.Skill_1_4,SkillData.Skill_1_5,SkillData.Skill_1_6,SkillData.Skill_1_6],
	},
	{
		Name : "克林塔尔",
		Desc : "来让我抱抱你",
		Icon : res.icon_hero_1,
		AtkBase : [0,0,8,0],
		MoneyBase : [0,8,9],
		SkillUnlock : [100,200,300,400,800,1000,1200],
		Skill : [SkillData.Skill_1_1,SkillData.Skill_1_2,SkillData.Skill_1_3,SkillData.Skill_1_4,SkillData.Skill_1_5,SkillData.Skill_1_6,SkillData.Skill_1_6],
	},
	{
		Name : "斯诺班",
		Desc : "肉动起来就很好切",
		Icon : res.icon_hero_1,
		AtkBase : [0,0,8,0],
		MoneyBase : [0,8,7],
		SkillUnlock : [100,200,300,400,800,1000,1200],
		Skill : [SkillData.Skill_1_1,SkillData.Skill_1_2,SkillData.Skill_1_3,SkillData.Skill_1_4,SkillData.Skill_1_5,SkillData.Skill_1_6,SkillData.Skill_1_6],
	},
	{
		Name : "泽弗洛斯特",
		Desc : "米沙，施放你的怒火",
		Icon : res.icon_hero_1,
		AtkBase : [0,0,8,0],
		MoneyBase : [0,8,7],
		SkillUnlock : [100,200,300,400,800,1000,1200],
		Skill : [SkillData.Skill_1_1,SkillData.Skill_1_2,SkillData.Skill_1_3,SkillData.Skill_1_4,SkillData.Skill_1_5,SkillData.Skill_1_6,SkillData.Skill_1_6],
	},
	{
		Name : "卡德里斯",
		Desc : "吾辈何以为战",
		Icon : res.icon_hero_1,
		AtkBase : [0,0,8,0],
		MoneyBase : [0,8,7],
		SkillUnlock : [100,200,300,400,800,1000,1200],
		Skill : [SkillData.Skill_1_1,SkillData.Skill_1_2,SkillData.Skill_1_3,SkillData.Skill_1_4,SkillData.Skill_1_5,SkillData.Skill_1_6,SkillData.Skill_1_6],
	},
	{
		Name : "芙兰朵露",
		Desc : "我的地狱火想摸摸你",
		Icon : res.icon_hero_1,
		AtkBase : [0,0,8,0],
		MoneyBase : [0,8,7],
		SkillUnlock : [100,200,300,400,800,1000,1200],
		Skill : [SkillData.Skill_1_1,SkillData.Skill_1_2,SkillData.Skill_1_3,SkillData.Skill_1_4,SkillData.Skill_1_5,SkillData.Skill_1_6,SkillData.Skill_1_6],
	},
	{
		Name : "米尔拉风暴",
		Desc : "闪电箭！闪电箭！闪电箭！",
		Icon : res.icon_hero_1,
		AtkBase : [0,0,8,0],
		MoneyBase : [0,8,7],
		SkillUnlock : [100,200,300,400,800,1000,1200],
		Skill : [SkillData.Skill_1_1,SkillData.Skill_1_2,SkillData.Skill_1_3,SkillData.Skill_1_4,SkillData.Skill_1_5,SkillData.Skill_1_6,SkillData.Skill_1_6],
	},
	{
		Name : "格雷兹怒拳",
		Desc : "你的脸可以释放我的怒火",
		Icon : res.icon_hero_1,
		AtkBase : [0,0,8,0],
		MoneyBase : [0,8,7],
		SkillUnlock : [100,200,300,400,800,1000,1200],
		Skill : [SkillData.Skill_1_1,SkillData.Skill_1_2,SkillData.Skill_1_3,SkillData.Skill_1_4,SkillData.Skill_1_5,SkillData.Skill_1_6,SkillData.Skill_1_6],
	},
	{
		Name : "马蒂亚斯",
		Desc : "你说你看到我了？对不起",
		Icon : res.icon_hero_1,
		AtkBase : [0,0,8,0],
		MoneyBase : [0,8,7],
		SkillUnlock : [100,200,300,400,800,1000,1200],
		Skill : [SkillData.Skill_1_1,SkillData.Skill_1_2,SkillData.Skill_1_3,SkillData.Skill_1_4,SkillData.Skill_1_5,SkillData.Skill_1_6,SkillData.Skill_1_6],
	},
	{
		Name : "霍克金斯",
		Desc : "你过得了我的盾么？",
		Icon : res.icon_hero_1,
		AtkBase : [0,0,8,0],
		MoneyBase : [0,8,7],
		SkillUnlock : [100,200,300,400,800,1000,1200],
		Skill : [SkillData.Skill_1_1,SkillData.Skill_1_2,SkillData.Skill_1_3,SkillData.Skill_1_4,SkillData.Skill_1_5,SkillData.Skill_1_6,SkillData.Skill_1_6],
	},
	{
		Name : "奥尔明燃须",
		Desc : "跟我的箭比比速度？",
		Icon : res.icon_hero_1,
		AtkBase : [0,0,8,0],
		MoneyBase : [0,8,7],
		SkillUnlock : [100,200,300,400,800,1000,1200],
		Skill : [SkillData.Skill_1_1,SkillData.Skill_1_2,SkillData.Skill_1_3,SkillData.Skill_1_4,SkillData.Skill_1_5,SkillData.Skill_1_6,SkillData.Skill_1_6],
	},
	{
		Name : "查沃卡",
		Desc : "圣光说你已经死了",
		Icon : res.icon_hero_1,
		AtkBase : [0,0,8,0],
		MoneyBase : [0,8,7],
		SkillUnlock : [100,200,300,400,800,1000,1200],
		Skill : [SkillData.Skill_1_1,SkillData.Skill_1_2,SkillData.Skill_1_3,SkillData.Skill_1_4,SkillData.Skill_1_5,SkillData.Skill_1_6,SkillData.Skill_1_6],
	},
	{
		Name : "斯汀克布莱德",
		Desc : "面对我的尖牙与利爪",
		Icon : res.icon_hero_1,
		AtkBase : [0,0,8,0],
		MoneyBase : [0,8,7],
		SkillUnlock : [100,200,300,400,800,1000,1200],
		Skill : [SkillData.Skill_1_1,SkillData.Skill_1_2,SkillData.Skill_1_3,SkillData.Skill_1_4,SkillData.Skill_1_5,SkillData.Skill_1_6,SkillData.Skill_1_6],
	},
	{
		Name : "地语者纳拉特",
		Desc : "萨满也是会发怒的",
		Icon : res.icon_hero_1,
		AtkBase : [0,0,8,0],
		MoneyBase : [0,8,7],
		SkillUnlock : [100,200,300,400,800,1000,1200],
		Skill : [SkillData.Skill_1_1,SkillData.Skill_1_2,SkillData.Skill_1_3,SkillData.Skill_1_4,SkillData.Skill_1_5,SkillData.Skill_1_6,SkillData.Skill_1_6],
	},
	{
		Name : "巫婆达尔芭",
		Desc : "你的灵魂在我手中燃烧",
		Icon : res.icon_hero_1,
		AtkBase : [0,0,8,0],
		MoneyBase : [0,8,7],
		SkillUnlock : [100,200,300,400,800,1000,1200],
		Skill : [SkillData.Skill_1_1,SkillData.Skill_1_2,SkillData.Skill_1_3,SkillData.Skill_1_4,SkillData.Skill_1_5,SkillData.Skill_1_6,SkillData.Skill_1_6],
	},
	{
		Name : "斯普鲁克",
		Desc : "爆一下就清净了",
		Icon : res.icon_hero_1,
		AtkBase : [0,0,8,0],
		MoneyBase : [0,8,7],
		SkillUnlock : [100,200,300,400,800,1000,1200],
		Skill : [SkillData.Skill_1_1,SkillData.Skill_1_2,SkillData.Skill_1_3,SkillData.Skill_1_4,SkillData.Skill_1_5,SkillData.Skill_1_6,SkillData.Skill_1_6],
	},
	{
		Name : "萨尤斯",
		Desc : "瘟疫为伴，死亡为友",
		Icon : res.icon_hero_1,
		AtkBase : [0,0,8,0],
		MoneyBase : [0,8,7],
		SkillUnlock : [100,200,300,400,800,1000,1200],
		Skill : [SkillData.Skill_1_1,SkillData.Skill_1_2,SkillData.Skill_1_3,SkillData.Skill_1_4,SkillData.Skill_1_5,SkillData.Skill_1_6,SkillData.Skill_1_6],
	},
	{
		Name : "克尔格鲁克",
		Desc : "鲁克认识你",
		Icon : res.icon_hero_1,
		AtkBase : [0,0,8,0],
		MoneyBase : [0,8,7],
		SkillUnlock : [100,200,300,400,800,1000,1200],
		Skill : [SkillData.Skill_1_1,SkillData.Skill_1_2,SkillData.Skill_1_3,SkillData.Skill_1_4,SkillData.Skill_1_5,SkillData.Skill_1_6,SkillData.Skill_1_6],
	},
	{
		Name : "布佛",
		Desc : "赤精会守护你",
		Icon : res.icon_hero_1,
		AtkBase : [0,0,8,0],
		MoneyBase : [0,8,7],
		SkillUnlock : [100,200,300,400,800,1000,1200],
		Skill : [SkillData.Skill_1_1,SkillData.Skill_1_2,SkillData.Skill_1_3,SkillData.Skill_1_4,SkillData.Skill_1_5,SkillData.Skill_1_6,SkillData.Skill_1_6],
	},
	{
		Name : "布瑟恩草风",
		Desc : "大自然会保护你",
		Icon : res.icon_hero_1,
		AtkBase : [0,0,8,0],
		MoneyBase : [0,8,7],
		SkillUnlock : [100,200,300,400,800,1000,1200],
		Skill : [SkillData.Skill_1_1,SkillData.Skill_1_2,SkillData.Skill_1_3,SkillData.Skill_1_4,SkillData.Skill_1_5,SkillData.Skill_1_6,SkillData.Skill_1_6],
	},
	{
		Name : "皮菲瑞多",
		Desc : "圣光能保护也能惩罚",
		Icon : res.icon_hero_1,
		AtkBase : [0,0,8,0],
		MoneyBase : [0,8,7],
		SkillUnlock : [100,200,300,400,800,1000,1200],
		Skill : [SkillData.Skill_1_1,SkillData.Skill_1_2,SkillData.Skill_1_3,SkillData.Skill_1_4,SkillData.Skill_1_5,SkillData.Skill_1_6,SkillData.Skill_1_6],
	},
	{
		Name : "布兰度尔铁锤",
		Desc : "剑盾猛攻，剑盾同眠",
		Icon : res.icon_hero_1,
		AtkBase : [0,0,8,0],
		MoneyBase : [0,8,7],
		SkillUnlock : [100,200,300,400,800,1000,1200],
		Skill : [SkillData.Skill_1_1,SkillData.Skill_1_2,SkillData.Skill_1_3,SkillData.Skill_1_4,SkillData.Skill_1_5,SkillData.Skill_1_6,SkillData.Skill_1_6],
	},
	{
		Name : "萨尤斯",
		Desc : "对不起你猜到的陷阱是我放的",
		Icon : res.icon_hero_1,
		AtkBase : [0,0,8,0],
		MoneyBase : [0,8,7],
		SkillUnlock : [100,200,300,400,800,1000,1200],
		Skill : [SkillData.Skill_1_1,SkillData.Skill_1_2,SkillData.Skill_1_3,SkillData.Skill_1_4,SkillData.Skill_1_5,SkillData.Skill_1_6,SkillData.Skill_1_6],
	},
	{
		Name : "高阶牧师劳瑞",
		Desc : "圣光学习哪家强？北郡暴风大教堂",
		Icon : res.icon_hero_1,
		AtkBase : [0,0,8,0],
		MoneyBase : [0,8,7],
		SkillUnlock : [100,200,300,400,800,1000,1200],
		Skill : [SkillData.Skill_1_1,SkillData.Skill_1_2,SkillData.Skill_1_3,SkillData.Skill_1_4,SkillData.Skill_1_5,SkillData.Skill_1_6,SkillData.Skill_1_6],
	},
	{
		Name : "派雷亚诺",
		Desc : "烧死这些异教徒",
		Icon : res.icon_hero_1,
		AtkBase : [0,0,8,0],
		MoneyBase : [0,8,7],
		SkillUnlock : [100,200,300,400,800,1000,1200],
		Skill : [SkillData.Skill_1_1,SkillData.Skill_1_2,SkillData.Skill_1_3,SkillData.Skill_1_4,SkillData.Skill_1_5,SkillData.Skill_1_6,SkillData.Skill_1_6],
	},
	{
		Name : "霍夫丹黑须",
		Desc : "我是冷动物不信你摸摸",
		Icon : res.icon_hero_1,
		AtkBase : [0,0,8,0],
		MoneyBase : [0,8,7],
		SkillUnlock : [100,200,300,400,800,1000,1200],
		Skill : [SkillData.Skill_1_1,SkillData.Skill_1_2,SkillData.Skill_1_3,SkillData.Skill_1_4,SkillData.Skill_1_5,SkillData.Skill_1_6,SkillData.Skill_1_6],
	},
	{
		Name : "德利兰特",
		Desc : "咕咕咕咕咕咕咕咕咕咕咕咕咕咕咕咕咕姑姑",
		Icon : res.icon_hero_1,
		AtkBase : [0,0,8,0],
		MoneyBase : [0,8,7],
		SkillUnlock : [100,200,300,400,800,1000,1200],
		Skill : [SkillData.Skill_1_1,SkillData.Skill_1_2,SkillData.Skill_1_3,SkillData.Skill_1_4,SkillData.Skill_1_5,SkillData.Skill_1_6,SkillData.Skill_1_6],
	},
	{
		Name : "米泽瑞",
		Desc : "红色代表了血液，这是你的",
		Icon : res.icon_hero_1,
		AtkBase : [0,0,8,0],
		MoneyBase : [0,8,7],
		SkillUnlock : [100,200,300,400,800,1000,1200],
		Skill : [SkillData.Skill_1_1,SkillData.Skill_1_2,SkillData.Skill_1_3,SkillData.Skill_1_4,SkillData.Skill_1_5,SkillData.Skill_1_6,SkillData.Skill_1_6],
	},
	{
		Name : "布瑞尔索恩",
		Desc : "我会把你的灵魂拖出来给你看看",
		Icon : res.icon_hero_1,
		AtkBase : [0,0,8,0],
		MoneyBase : [0,8,7],
		SkillUnlock : [100,200,300,400,800,1000,1200],
		Skill : [SkillData.Skill_1_1,SkillData.Skill_1_2,SkillData.Skill_1_3,SkillData.Skill_1_4,SkillData.Skill_1_5,SkillData.Skill_1_6,SkillData.Skill_1_6],
	},
	{
		Name : "汉斯冷炉",
		Desc : "冷静一下，或者冷冻一下",
		Icon : res.icon_hero_1,
		AtkBase : [0,0,8,0],
		MoneyBase : [0,8,7],
		SkillUnlock : [100,200,300,400,800,1000,1200],
		Skill : [SkillData.Skill_1_1,SkillData.Skill_1_2,SkillData.Skill_1_3,SkillData.Skill_1_4,SkillData.Skill_1_5,SkillData.Skill_1_6,SkillData.Skill_1_6],
	},	
];

function getHeroAtk(hero) {
	return hero.AtkBase;
}
function getHeroMoney(hero) {
	return hero.MoneyBase;
}



